version: "3.3"
services:

    nginx_front:
        image: nginx:1.21.6-alpine
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "127.0.0.1:80:80"
        networks:
            frontend:
                ipv4_address: 172.16.235.10
            backend:
                ipv4_address: 172.16.236.10
        entrypoint: ["nginx", "-c", "/etc/nginx/nginx.conf"]

    flask_back:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.app
        image: pystringer
        expose:
            - "8888"
        networks:
            backend:
                ipv4_address: 172.16.236.11

networks:
    frontend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.235.0/24"

    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.236.0/24"
