* pystringer project
** Description
- This is a hello-world containerized Flask app that expects a string in POST payload and responds with a result pretty much like a CLI utility.
** Deployment
- The service is deployed at localhost by default.
- Port 80 is served by nginx.
- Grafana is available at ~http://127.0.0.1/grafana~ with admin:admin login pair.
- Grafana provides total request count graph in pystringer dashboard.
#+BEGIN_SRC sh

### from the project root
$ docker-compose up -d

#+END_SRC
** Usage
- By default, nginx frontend listens on 127.0.0.1:80 and forwards requests to uWSGI running in a separate container.
- Make sure you have ~curl~ installed.

#+BEGIN_SRC sh

### get list of valid requests
$ curl http://127.0.0.1                            
Valid requests: lowercase, uppercase, reverse, randomcase

### convert a string to lowercase
$ curl -d 'LOREM IPSUM DOLOR SIT AMET' http://127.0.0.1/lowercase                                                                       
lorem ipsum dolor sit ame

### convert a string to uppercase
$ curl -d 'lorem ipsum dolor sit ame' http://127.0.0.1/uppercase
LOREM IPSUM DOLOR SIT AME

### convert a string to randomcase (that's my favorite)
$ curl -d 'lorem ipsum dolor sit ame' http://127.0.0.1/randomcase
loReM ipsuM DOloR SIt AME

### reverse a string
$ curl -d 'lorem ipsum dolor sit ame' http://127.0.0.1/reverse   
ema tis rolod muspi merol

#+END_SRC
** Testing
- Unit testing is implemented as a simple infinite loop that selects a method randomly on each iteration, generates a random string, and asserts against a known result.
- Also, it's quite useful to populate metrics with some data.

#+BEGIN_SRC sh

### make sure you have requests module installed
$ python3 app_test.py
randomcase: cfrrxczxrpblfailvgilbaljpcststqfhcjwdvyfb
response: cfrRxCZXrpbLFAiLVGilBALjpCSTSTQFhcjwdVyFB
**************************************************
lowercase: dbrgkrktghz
response: dbrgkrktghz
**************************************************
...

#+END_SEC
