apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:

  prometheus.yaml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
    rule_files:
      - alert.yaml
    scrape_configs:
      - job_name: pystringer-mon
        metrics_path: /metrics
        static_configs:
          - targets: ["nginx-front:80"]

  alert.yaml: |
    groups:
      - name: VitalSigns
        rules:
          - alert: NginxIsDown
            expr: up{job="services"} < 1
            for: 5m
