global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: pystringer_mon
    metrics_path: /metrics
    static_configs:
        - targets: ["nginx_front:80"]
