apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: default
data:

  datasources-default.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        editable: false
        is_default: true
        access: proxy
        url: http://127.0.0.1:9090

  dashboards-default.yaml: |
    apiVersion: 1
    providers:
      - name: prometheus
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards

  grafana.ini: |
    [server]
    domain = 127.0.0.1
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
    serve_from_sub_path = true
